services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
    tty: true
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/dashboard"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: p@ssw0rd

  db:
    platform: linux/amd64
    build: ./db
    environment:
      - MYSQL_DATABASE=dashboard
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
    volumes:
      - ./db/my.cnf:/etc/my.cnf
      - ./db/:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development